# Generated by Django 3.1.7 on 2021-03-12 19:19

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='desc',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
    ]
